name: covid-polygraph
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.4.0
  - asgiref=3.4.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.14.6
  - charset-normalizer=2.0.9
  - click=8.0.3
  - colorama=0.4.4
  - configparser=5.2.0
  - cpuonly=2.0
  - cryptography=35.0.0
  - dataclasses=0.8
  - fastapi=0.70.1
  - ffmpeg=4.3
  - filelock=3.4.2
  - freetype=2.11.0
  - future=0.18.2
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - h11=0.12.0
  - huggingface_hub=0.2.1
  - idna=3.1
  - importlib-metadata=4.10.0
  - importlib_metadata=4.10.0
  - intel-openmp=2021.4.0
  - joblib=1.1.0
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - minio=7.1.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1l
  - packaging=21.3
  - pillow=8.4.0
  - pip=21.2.4
  - pycparser=2.21
  - pydantic=1.8.2
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python-multipart=0.0.5
  - python_abi=3.8
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - pytz=2021.3
  - pyyaml=5.4.1
  - readline=8.1
  - regex=2021.8.3
  - requests=2.26.0
  - sacremoses=0.0.46
  - setuptools=58.0.4
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.37.0
  - starlette=0.16.0
  - tk=8.6.11
  - tokenizers=0.10.3
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - tqdm=4.62.3
  - transformers=4.15.0
  - typing-extensions=4.0.1
  - typing_extensions=4.0.1
  - urllib3=1.26.7
  - uvicorn=0.16.0
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - captum==0.4.1
    - cycler==0.11.0
    - fonttools==4.28.5
    - kiwisolver==1.3.2
    - matplotlib==3.5.1
    - transformers-interpret==0.5.2
